# Generated by Django 4.1.1 on 2022-09-13 06:12

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('tipoIdentificacion', models.CharField(max_length=255)),
                ('numeroIdentificacion', models.IntegerField(primary_key=True, serialize=False, verbose_name=builtins.id)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('correoElectronico', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('rol', models.CharField(max_length=200, verbose_name='rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(default='General', max_length=200)),
                ('registro', models.CharField(max_length=256)),
                ('numeroUdentificacionUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateField(blank=True)),
                ('direccion', models.CharField(max_length=250)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medico', to='hospitalApp.medico', unique=True)),
                ('numeroIdentificacionUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('oximetria', models.CharField(max_length=250)),
                ('frecuenciaRespiratoria', models.IntegerField()),
                ('frecuenciaCardiaca', models.IntegerField()),
                ('temperatura', models.CharField(max_length=250)),
                ('glucemia', models.IntegerField()),
                ('presionArterial', models.CharField(max_length=250)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.paciente', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaActualizacion', models.DateField()),
                ('examenFisico', models.TextField(blank=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('evolucion', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('idMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.medico', unique=True)),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.paciente', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Paciente', to='hospitalApp.paciente', unique=True)),
                ('numeroIdentificacionUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroIdentificacionUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
